[theme]
primaryColor = "#1E2250"             # Yellow - like Mercado Livre buttom
backgroundColor = "#ffffff"          # Light yellow for the background
secondaryBackgroundColor = "#f5f5f5" # Light blue for widget background
textColor = "#2d377a"                # Blue - like Mercado Livre text
font = "sans serif"